base_images:
  os:
    name: ubi
    namespace: ocp
    tag: "7"
binary_build_commands: make build
build_root:
  project_image:
    dockerfile_path: openshift-ci/Dockerfile.tools
resources:
  '*':
    requests:
      cpu: 100m
      memory: 250Mi
tag_specification:
  name: "4.6"
  namespace: ocp
tests:
- as: acceptance
  steps:
    cluster_profile: aws
    test:
    - as: test
      cli: latest
      commands: CONTAINER_RUNTIME=podman OPERATOR_REPO_REF=$(cat /usr/local/secrets/quay.credentials | cut -d "=" -f1) OPERATOR_INDEX_IMAGE_REF=$(cat /usr/local/secrets/quay.credentials | cut -d "=" -f1):index-$PULL_PULL_SHA QUAY_USERNAME=$(cat /usr/local/secrets/quay.credentials | cut -d "=" -f2) QUAY_TOKEN=$(cat /usr/local/secrets/quay.credentials | cut -d "=" -f3) VERBOSE=2 make -k release-operator test-acceptance-with-bundle test-acceptance-artifacts
      credentials:
      - mount_path: /usr/local/secrets
        name: rhd-sbo-test-quay-credentials
        namespace: test-credentials
      from: src
      resources:
        requests:
          cpu: 100m
    workflow: ipi-aws
- as: validate-master-build
  cron: 0 0 * * *
  steps:
    cluster_profile: aws
    test:
    - as: test
      cli: latest
      commands: VERBOSE=2 make -k test-acceptance-with-bundle test-acceptance-artifacts
      from: src
      resources:
        requests:
          cpu: 100m
    workflow: ipi-aws
zz_generated_metadata:
  branch: master
  org: redhat-developer
  repo: service-binding-operator
  variant: "4.6"
